# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAc4-ZvI58lH3VMjkVpBySOEWAqgw3kx

#assignment 2
#variable 1
"""

#  Write a program that swaps the values of two variables.

a = 10
b = 20
print("Before swapping: a =", a, "b =", b)
a, b = b, a
print("After swapping: a =", a, "b =", b)

length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))
area = length * width
print("The area of the rectangle is:", area)

#  Write a program that converts temperature from Fahrenheit to Celsius.

fahrenheit = float(input("Enter the temperature in Fahrenheit: "))
celsius = (fahrenheit - 32) * 5 / 9
print("The temperature in Celsius is:", celsius)

#  Write a program that calculates the volume of a sphere given its radius.

radius = float(input("Enter the radius of the sphere: "))
volume = (4/3) * 3.14 * radius ** 3
print("The volume of the sphere is:", volume)

8#  Write a program that finds the average of three numbers.

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

average = (a + b + c) / 3

print("The average of three numbers is:", average)

"""If-elif-else

"""

#  Write a program that determines if a number is even or odd.

num = int(input("Enter a number: "))
if num % 2 == 0:
  print(num, "is even")
else:
  print(num, "is odd")

#  Write a program that finds the maximum of three numbers.

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

if a > b and a > c:
  print("The maximum number is:", a)
elif b > a and b > c:
  print("The maximum number is:", b)
else:
  print("The maximum number is:", c)

#  Write a program that determines if a year is a leap year or not.

year = int(input("Enter a year: "))

if year % 4 == 0:
  if year % 100 == 0:
    if year % 400 == 0:
      print(year, "is a leap year")
    else:
      print(year, "is not a leap year")
  else:
    print(year, "is a leap year")
else:
  print(year, "is not a leap year")

# prompt: Write a program that determines if a number is positive, negative, or zero.

num = float(input("Enter a number: "))
if num > 0:
  print(num, "is positive")
elif num < 0:
  print(num, "is negative")
else:
  print(num, "is zero")

# prompt: Write a program that calculates the grade based on a given percentage.

percentage = float(input("Enter your percentage: "))
if percentage >= 90:
  print("Grade: A+")
elif percentage >= 80:
  print("Grade: A")
elif percentage >= 70:
  print("Grade: B")
elif percentage >= 60:
  print("Grade: C")
elif percentage >= 50:
  print("Grade: D")
else:
  print("Grade: F")

"""For Loop

"""

#  Write a program that prints the first `n` natural numbers.

n = int(input("Enter the value of n: "))
for i in range(1, n + 1):
  print(i)

# prompt: Write a program that calculates the factorial of a number.

def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n - 1)

num = int(input("Enter a number: "))
print("The factorial of", num, "is", factorial(num))

# prompt: Write a program that generates a Fibonacci sequence of length `n`.

def fibonacci(n):
  if n <= 1:
    return n
  else:
    return fibonacci(n - 1) + fibonacci(n - 2)

n = int(input("Enter the length of the Fibonacci sequence: "))
print("The Fibonacci sequence of length", n, "is:")
for i in range(n):
  print(fibonacci(i))

# prompt: Write a program that checks if a given number is prime or not.

num = int(input("Enter a number: "))
if num > 1:
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

# prompt: Write a program that prints the multiplication table of a given number.

num = int(input("Enter a number: "))
for i in range(1, 11):
  print(num, "x", i, "=", num * i)

"""while loop"""

#  Write a program that finds the sum of all even numbers between 1 and `n`.

n = int(input("Enter the value of n: "))
sum = 0
i = 1
while i <= n:
  if i % 2 == 0:
    sum += i
  i += 1
print("The sum of all even numbers between 1 and", n, "is", sum)

#  Write a program that reverses a given number.

num = int(input("Enter a number: "))
reversed_num = 0
while num > 0:
  reversed_num = reversed_num * 10 + num % 10
  num //= 10
print("The reversed number is:", reversed_num)

#  Write a program that checks if a given string is a palindrome.
def is_palindrome(s):
    # Remove spaces and convert to lowercase for case-insensitive comparison
    s = s.replace(" ", "").lower()

    # Compare the original string with its reverse
    return s == s[::-1]

# Get input from the user
user_input = input("Enter a string: ")

# Check if the input is a palindrome
if is_palindrome(user_input):
    print("Yes, it is a palindrome.")
else:
    print("No, it is not a palindrome.")

#  Write a program that generates a random number and allows the user to guess it.
import random

def guess_the_number():
    # Generate a random number between 1 and 100
    secret_number = random.randint(1, 100)

    attempts = 0

    print("Welcome to Guess the Number Game!")
    print("I have chosen a number between 1 and 100. Try to guess it.")

    while True:
        # Get user input for a guess
        user_guess = int(input("Enter your guess: "))

        # Increment the attempts count
        attempts += 1

        # Check if the guess is correct
        if user_guess == secret_number:
            print(f"Congratulations! You guessed the number {secret_number} in {attempts} attempts.")
            break
        elif user_guess < secret_number:
            print("Too low. Try again.")
        else:
            print("Too high. Try again.")

# Run the game
guess_the_number()

#Write a program that finds the greatest common divisor (GCD) of two numbers.
import math

# prints 12
print("The gcd of 60 and 48 is : ", end="")
print(math.gcd(60, 48))